version: '3'
services:
  standalone:
    image: "grubykarol/locust:0.8.1-py3.6"
    container_name: standalone
    hostname: standalone
    ports:
     - "8089:8089"
    environment:
      ATTACKED_HOST: https://au-metro-transformer.dev.aumetros.djservices.io
      LOCUST_MODE: standalone
      NO_PROXY: standalone
      TASK_DELAY_FROM: 5
      TASK_DELAY_TO: 30
      QUIET_MODE: "${QUIET_MODE:-false}"
      LOCUST_OPTS: "--web-port 8089"
    volumes:
      - ./locust-scripts:/locust